# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{processr}
  s.version = "0.9.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Nesbitt"]
  s.date = %q{2010-09-21}
  s.description = %q{Processr is a simple text processing and concatenation library. It takes a number of input strings (or files) and outputs a single string (or file) containing the result. Text can be passed through filters to modify the output.}
  s.email = %q{josh@josh-nesbitt.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "Rakefile",
     "TODO",
     "VERSION",
     "examples/all.rb",
     "lib/processr.rb",
     "processr.gemspec",
     "readme.rdoc",
     "spec/fixtures/one.txt",
     "spec/fixtures/output.txt",
     "spec/fixtures/two.txt",
     "spec/lib/processr_spec.rb",
     "spec/spec_helper.rb",
     "spec/watch.rb"
  ]
  s.homepage = %q{http://github.com/joshnesbitt/processr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple text processing library}
  s.test_files = [
    "spec/lib/processr_spec.rb",
     "spec/spec_helper.rb",
     "spec/watch.rb",
     "examples/all.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

